export const szamarLISTA=[
    {
    nev:"shadow",
    fajta:"Poitou",
    szin:"fekete",
    magassag:"160",
    szul_datum:"2024.04.01", 
    ar:"300000ft" ,
    kep:"kepek/poitou.png",
    termekleiras:"A Poitou szamárnak hosszú, tüsi hajszőre van, különleges megjelenésű és jól alkalmazkodott a nehéz munkához.",

    },
    
    {
    nev:"Dolly",
    fajta:"Andalusian",
    szin:"barna",
    magassag:"150",
    szul_datum:"2023.11.04",
    ar:"250000ft",
    kep:"kepek/andalusian.png",
    termekleiras:"Az andalúz ló elegáns megjelenésű, híres kiegyensúlyozott természetéről és magas szintű teljesítményéről, különösen a klasszikus lovas művészetek terén.",
    },
    {
    nev:"Grafit",
    fajta:"Amiatina",
    szin:"barna",
    magassag:"140",
    szul_datum:"2022.01.04",
    ar:"180000ft",
    kep:"kepek/amiatian.png",
    termekleiras:"Az Amiatina egy ritka olasz szamarafajta, melyet az Amiata-hegyek területén tenyésztenek, jellegzetes hosszú, dús szőrével és erős testfelépítésével.",
    },
    {
    nev:"Rumli",
    fajta:"Bourbonnais",
    szin:"fehér",
    magassag:"170",
    szul_datum:"2023.06.23",
    ar:"340783ft",
    kep:"kepek/Bourbonnais.png",
    termekleiras:"A Bourbonnais szamár Franciaországban őshonos, közepes méretű, erős, de elegáns megjelenésű fajta.",
    } , 
    {
    nev:"samantha",
    fajta:"cotentin ",
    szin:"fekete",
    magassag:"155",
    szul_datum:"2020.04.25",
    ar:"169999ft",
    kep:"kepek/cotentin.png",
    termekleiras:"A Cotentin szamár egy kis termetű, robusztus fajta, melyet hagyományosan mezőgazdasági munkákra tenyésztenek, és jellegzetes szürkésbarna színével és erős testfelépítésével rendelkezik.",
    },  
    {
    nev:"Hamu",
    fajta:"zamorano-leonés",
    szin:"szürke",
    magassag:"157",
    szul_datum:"2024.04.07",
    ar:"200000ft",
    kep:"kepek/zamorano.png",
    termekleiras:"A Zamorano-Leonés szamár egy spanyol fajta, amelyet hagyományosan mezőgazdasági munkákra és teherhordásra használtak, különleges megjelenésű, erős testfelépítésű állat.",
    }
]
